#spring:
#  profiles:
#    active: productions

spring:
#  profiles:
#    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/middle
    username: root
    password: xuhaoranaaa.
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

server:
  servlet:
    context-path: /middleware
  port: 8001

#logging日志配置
logging:
  level:
    root: WARN
    org:
      springframework: INFO
      jackson: INFO
    com:
      study:
        middleware: DEBUG
  config: classpath:logback.xml

# 数据库配置
#Mybatis配置

